name: Update Website

on: 
    push:
        branches:
        - master

jobs:
    build:
        runs-on: ubuntu-latest
        environment: ${{github.ref_name}}
        steps:
        - name: update
          run: |
            curl "${{secrets.RENDER_DEPLOY_HOOK_URL}}" 